"use client";

import { useState, useEffect, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Mic,
  MicOff,
  Volume2,
  RotateCcw,
  FileText,
  LogOut,
  User,
  Circle,
  Check,
  Sparkles,
  Clock,
  Download,
  Play,
  Send,
  ChevronRight,
  MessageSquare,
  Loader2,
} from "lucide-react";
import {
  generateInterviewQuestions,
  evaluateInterviewAnswers,
  InterviewQuestion,
  InterviewFeedback,
} from "@/lib/gemini";

interface Answer {
  questionId: number;
  text: string;
  duration: number;
}

interface SetupConfig {
  position: string;
  level: string;
  language: string;
  duration: string;
  questionCount: string;
}

interface AIInterviewPageProps {
  config: SetupConfig;
  onExit: () => void;
  onNavigateToSubmitCV?: () => void;
}

// Questions will be generated by Gemini AI based on config

/* eslint-disable @typescript-eslint/no-explicit-any */
declare global {
  interface Window {
    SpeechRecognition: any;
    webkitSpeechRecognition: any;
  }
}
/* eslint-enable @typescript-eslint/no-explicit-any */

export function AIInterviewPage({ config, onExit, onNavigateToSubmitCV }: AIInterviewPageProps) {
  const [questions, setQuestions] = useState<InterviewQuestion[]>([]);
  const [isLoadingQuestions, setIsLoadingQuestions] = useState(true);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [isRecording, setIsRecording] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [recordingTime, setRecordingTime] = useState(0);
  const [answers, setAnswers] = useState<Answer[]>([]);
  const [isCompleted, setIsCompleted] = useState(false);
  const [showTranscript, setShowTranscript] = useState(false);
  const [showPermissionModal, setShowPermissionModal] = useState(false);
  const [currentTranscript, setCurrentTranscript] = useState("");
  const [aiFeedback, setAiFeedback] = useState<InterviewFeedback | null>(null);
  const [isLoadingFeedback, setIsLoadingFeedback] = useState(false);

  const timerRef = useRef<NodeJS.Timeout | null>(null);
  /* eslint-disable @typescript-eslint/no-explicit-any */
  const recognitionRef = useRef<any>(null);
  /* eslint-enable @typescript-eslint/no-explicit-any */

  const currentQuestion = questions[currentQuestionIndex];
  const maxRecordingTime = 120; // 2 minutes per answer

  // Load câu hỏi từ Gemini AI khi component mount
  useEffect(() => {
    async function loadQuestions() {
      setIsLoadingQuestions(true);
      try {
        const generatedQuestions = await generateInterviewQuestions(
          config.position,
          config.level,
          config.language,
          parseInt(config.questionCount) || 5
        );
        setQuestions(generatedQuestions);
      } catch (error) {
        console.error("Failed to load questions:", error);
        alert("Không thể tải câu hỏi từ AI. Vui lòng thử lại.");
      } finally {
        setIsLoadingQuestions(false);
      }
    }

    loadQuestions();
  }, [config]);

  // Load feedback từ Gemini khi hoàn thành
  useEffect(() => {
    async function loadFeedback() {
      if (isCompleted && !aiFeedback && answers.length > 0 && questions.length > 0) {
        setIsLoadingFeedback(true);
        try {
          const feedback = await evaluateInterviewAnswers(
            config.position,
            config.level,
            questions,
            answers
          );
          setAiFeedback(feedback);
        } catch (error) {
          console.error("Failed to load feedback:", error);
        } finally {
          setIsLoadingFeedback(false);
        }
      }
    }

    loadFeedback();
  }, [isCompleted, aiFeedback, answers, config, questions]);

  // Speech Synthesis - read question aloud
  const speakQuestion = (text: string) => {
    if ("speechSynthesis" in window) {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = config.language === "vi" ? "vi-VN" : "en-US";
      utterance.rate = 0.9;
      utterance.pitch = 1;

      utterance.onstart = () => setIsSpeaking(true);
      utterance.onend = () => setIsSpeaking(false);

      window.speechSynthesis.speak(utterance);
    }
  };

  // Read question when changing question
  useEffect(() => {
    if (currentQuestion && !isCompleted) {
      speakQuestion(currentQuestion.text);
    }
    return () => {
      if ("speechSynthesis" in window) {
        window.speechSynthesis.cancel();
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentQuestionIndex, currentQuestion, isCompleted, config.language]);

  // Check microphone permission
  const checkMicrophonePermission = async () => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      stream.getTracks().forEach(track => track.stop());
      return true;
    } catch {
      setShowPermissionModal(true);
      return false;
    }
  };

  // Start recording
  const startRecording = async () => {
    if (!("webkitSpeechRecognition" in window || "SpeechRecognition" in window)) {
      alert("Trình duyệt không hỗ trợ ghi âm. Vui lòng sử dụng Chrome.");
      return;
    }

    const hasPermission = await checkMicrophonePermission();
    if (!hasPermission) return;

    const SpeechRecognitionAPI = window.SpeechRecognition || window.webkitSpeechRecognition;
    recognitionRef.current = new SpeechRecognitionAPI();
    recognitionRef.current.continuous = true;
    recognitionRef.current.interimResults = true;
    recognitionRef.current.lang = config.language === "vi" ? "vi-VN" : "en-US";

    setCurrentTranscript("");

    /* eslint-disable @typescript-eslint/no-explicit-any */
    recognitionRef.current.onresult = (event: any) => {
      let interimTranscript = "";
      let finalTranscript = "";

      for (let i = event.resultIndex; i < event.results.length; i++) {
        const transcript = event.results[i][0].transcript;
        if (event.results[i].isFinal) {
          finalTranscript += transcript + " ";
        } else {
          interimTranscript += transcript;
        }
      }

      setCurrentTranscript(finalTranscript || interimTranscript);
    };

    recognitionRef.current.onerror = (event: any) => {
    /* eslint-enable @typescript-eslint/no-explicit-any */
      if (event.error === "not-allowed" || event.error === "permission-denied") {
        setShowPermissionModal(true);
      }
      stopRecording();
    };

    try {
      recognitionRef.current.start();
      setIsRecording(true);
      setRecordingTime(0);

      timerRef.current = setInterval(() => {
        setRecordingTime((prev) => {
          if (prev >= maxRecordingTime - 1) {
            stopRecording();
            return maxRecordingTime;
          }
          return prev + 1;
        });
      }, 1000);
    } catch {
      setShowPermissionModal(true);
    }
  };

  // Stop recording
  const stopRecording = () => {
    if (recognitionRef.current) {
      recognitionRef.current.stop();
      recognitionRef.current = null;
    }

    if (timerRef.current) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }

    setIsRecording(false);

    // Save answer
    const newAnswer: Answer = {
      questionId: currentQuestion.id,
      text: currentTranscript || "(Không có câu trả lời)",
      duration: recordingTime,
    };

    setAnswers((prev) => [...prev, newAnswer]);
    setCurrentTranscript("");
  };

  // Next question
  const nextQuestion = () => {
    if (currentQuestionIndex < questions.length - 1) {
      setCurrentQuestionIndex((prev) => prev + 1);
      setRecordingTime(0);
    } else {
      setIsCompleted(true);
    }
  };

  // Repeat question
  const repeatQuestion = () => {
    if (currentQuestion) {
      speakQuestion(currentQuestion.text);
    }
  };

  // Exit interview
  const exitInterview = () => {
    if (window.confirm("Bạn có chắc muốn thoát buổi phỏng vấn?")) {
      window.speechSynthesis.cancel();
      if (recognitionRef.current) {
        recognitionRef.current.stop();
      }
      if (timerRef.current) {
        clearInterval(timerRef.current);
      }
      onExit();
    }
  };

  // Format time
  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  // Loading screen khi đang tải câu hỏi
  if (isLoadingQuestions) {
    return (
      <div className="min-h-screen bg-[#ECF4D6] flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-16 h-16 text-[#2D9596] animate-spin mx-auto mb-4" />
          <p className="text-[#265073] text-xl mb-2">Đang tạo câu hỏi phỏng vấn...</p>
          <p className="text-[#2D9596] text-sm">AI đang phân tích vị trí {config.position} level {config.level}</p>
        </div>
      </div>
    );
  }

  // Results screen
  if (isCompleted) {
    return (
      <div className="min-h-screen bg-[#ECF4D6] py-12">
        <div className="max-w-4xl mx-auto px-6">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white rounded-2xl shadow-xl overflow-hidden"
          >
            {/* Header */}
            <div className="bg-gradient-to-r from-[#265073] to-[#2D9596] text-white p-8 text-center">
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                transition={{ delay: 0.2 }}
                className="w-20 h-20 bg-white rounded-full mx-auto mb-4 flex items-center justify-center"
              >
                <Check className="w-10 h-10 text-[#2D9596]" />
              </motion.div>
              <h2 className="text-3xl mb-2">Hoàn thành buổi phỏng vấn!</h2>
              <p className="text-[#9AD0C2]">
                Bạn đã trả lời {answers.length}/{questions.length} câu hỏi
              </p>
            </div>

            {/* AI Feedback */}
            <div className="p-8">
              {isLoadingFeedback ? (
                <div className="mb-8 p-6 bg-gradient-to-br from-[#ECF4D6] to-white rounded-xl border-2 border-[#9AD0C2] flex items-center justify-center min-h-[200px]">
                  <div className="text-center">
                    <Loader2 className="w-12 h-12 text-[#2D9596] animate-spin mx-auto mb-3" />
                    <p className="text-[#265073]">AI đang phân tích câu trả lời của bạn...</p>
                    <p className="text-sm text-[#2D9596] mt-1">Vui lòng đợi trong giây lát</p>
                  </div>
                </div>
              ) : aiFeedback ? (
                <div className="mb-8 p-6 bg-gradient-to-br from-[#ECF4D6] to-white rounded-xl border-2 border-[#9AD0C2]">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 bg-[#2D9596] rounded-full flex items-center justify-center">
                      <Sparkles className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <h3 className="text-[#265073] text-lg">Đánh giá từ Gemini AI</h3>
                      <p className="text-sm text-[#2D9596]">
                        Điểm tổng: <strong className="text-lg">{aiFeedback.overallScore}/100</strong>
                      </p>
                    </div>
                  </div>
                  <p className="text-[#265073] leading-relaxed mb-4 whitespace-pre-line">
                    {aiFeedback.detailedFeedback}
                  </p>
                  
                  <div className="space-y-4 mt-6">
                    {/* Strengths */}
                    <div>
                      <p className="text-sm font-semibold text-[#265073] mb-2">✅ Điểm mạnh:</p>
                      <div className="space-y-2">
                        {aiFeedback.strengths.map((strength, index) => (
                          <div key={index} className="flex items-start gap-3">
                            <Check className="w-5 h-5 text-green-500 flex-shrink-0 mt-0.5" />
                            <p className="text-sm text-[#265073]">{strength}</p>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Improvements */}
                    <div>
                      <p className="text-sm font-semibold text-[#265073] mb-2">📈 Cần cải thiện:</p>
                      <div className="space-y-2">
                        {aiFeedback.improvements.map((improvement, index) => (
                          <div key={index} className="flex items-start gap-3">
                            <span className="w-5 h-5 bg-orange-500 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5 text-white text-xs">
                              !
                            </span>
                            <p className="text-sm text-[#265073]">{improvement}</p>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              ) : (
                <div className="mb-8 p-6 bg-gradient-to-br from-[#ECF4D6] to-white rounded-xl border-2 border-[#9AD0C2]">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 bg-[#2D9596] rounded-full flex items-center justify-center">
                      <Sparkles className="w-6 h-6 text-white" />
                    </div>
                    <div>
                      <h3 className="text-[#265073]">Đánh giá từ AI</h3>
                      <p className="text-sm text-[#2D9596]">Không có dữ liệu đánh giá</p>
                    </div>
                  </div>
                </div>
              )}

              {/* Answers List */}
              <div className="space-y-4">
                <h3 className="text-[#265073] flex items-center gap-2 mb-4">
                  <FileText className="w-5 h-5" />
                  Câu trả lời của bạn
                </h3>
                {answers.map((answer, index) => {
                  const question = questions.find((q) => q.id === answer.questionId);
                  const feedback = aiFeedback?.questionFeedbacks.find(
                    (f) => f.questionId === answer.questionId
                  );
                  return (
                    <motion.div
                      key={answer.questionId}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.1 }}
                      className="p-5 bg-[#ECF4D6] rounded-xl border border-[#9AD0C2]"
                    >
                      <div className="flex items-start justify-between gap-3 mb-2">
                        <div className="flex items-start gap-3 flex-1">
                          <span className="flex-shrink-0 w-7 h-7 bg-[#2D9596] text-white rounded-full flex items-center justify-center text-sm">
                            {index + 1}
                          </span>
                          <div className="flex-1">
                            <p className="text-[#265073] mb-1">{question?.text}</p>
                            {feedback && (
                              <div className="flex items-center gap-2 mt-1">
                                <span className="text-xs bg-[#2D9596] text-white px-2 py-0.5 rounded-full">
                                  Điểm: {feedback.score}/10
                                </span>
                                {question?.difficulty && (
                                  <span className="text-xs bg-gray-200 text-gray-700 px-2 py-0.5 rounded-full">
                                    {question.difficulty === "easy"
                                      ? "Dễ"
                                      : question.difficulty === "medium"
                                      ? "Trung bình"
                                      : "Khó"}
                                  </span>
                                )}
                              </div>
                            )}
                          </div>
                        </div>
                        <div className="flex gap-2">
                          <button
                            onClick={() => {
                              const utterance = new SpeechSynthesisUtterance(answer.text);
                              utterance.lang = config.language === "vi" ? "vi-VN" : "en-US";
                              window.speechSynthesis.speak(utterance);
                            }}
                            className="p-2 bg-[#2D9596] text-white rounded-lg hover:bg-[#265073] transition-all"
                            title="Nghe lại"
                          >
                            <Play className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => {
                              const blob = new Blob([answer.text], { type: "text/plain" });
                              const url = URL.createObjectURL(blob);
                              const a = document.createElement("a");
                              a.href = url;
                              a.download = `answer-${index + 1}.txt`;
                              a.click();
                            }}
                            className="p-2 bg-[#265073] text-white rounded-lg hover:bg-[#2D9596] transition-all"
                            title="Tải xuống"
                          >
                            <Download className="w-4 h-4" />
                          </button>
                        </div>
                      </div>
                      <div className="ml-10 mt-3 space-y-3">
                        <div className="p-4 bg-white rounded-lg">
                          <p className="text-sm text-[#265073] leading-relaxed">
                            {answer.text}
                          </p>
                          <div className="flex items-center gap-2 mt-3 text-xs text-[#2D9596]">
                            <Clock className="w-3 h-3" />
                            <span>Thời gian: {answer.duration}s</span>
                          </div>
                        </div>
                        {feedback && feedback.feedback && (
                          <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
                            <p className="text-xs text-blue-900 leading-relaxed">
                              <strong>💡 Nhận xét AI:</strong> {feedback.feedback}
                            </p>
                          </div>
                        )}
                      </div>
                    </motion.div>
                  );
                })}
              </div>

              {/* Actions */}
              <div className="flex gap-4 mt-8">
                <button
                  onClick={onExit}
                  className="flex-1 py-3 bg-[#2D9596] text-white rounded-xl hover:bg-[#265073] transition-all duration-300"
                >
                  Phỏng vấn lại
                </button>
                <button
                  onClick={() => {
                    if (onNavigateToSubmitCV) {
                      onNavigateToSubmitCV();
                    }
                  }}
                  className="flex-1 py-3 bg-[#265073] text-white rounded-xl hover:bg-[#2D9596] transition-all duration-300 flex items-center justify-center gap-2"
                >
                  <Send className="w-5 h-5" />
                  Gửi kết quả cùng CV
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    );
  }

  // Interview screen
  return (
    <div className="min-h-screen bg-[#ECF4D6] flex flex-col">
      {/* Header */}
      <header className="h-[60px] bg-[#265073] flex items-center justify-between px-6 shadow-lg">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 bg-[#2D9596] rounded-lg flex items-center justify-center">
            <Sparkles className="w-6 h-6 text-white" />
          </div>
          <span className="text-white">AI Interview</span>
        </div>
        <h1 className="text-white text-lg">Phỏng vấn cùng AI</h1>
        <div className="flex items-center gap-3">
          <div className="text-right mr-2 hidden md:block">
            <p className="text-white text-sm">Câu hỏi {currentQuestionIndex + 1}/{questions.length}</p>
            <p className="text-[#9AD0C2] text-xs">{formatTime(recordingTime)}</p>
          </div>
          <div className="w-10 h-10 bg-[#9AD0C2] rounded-full flex items-center justify-center">
            <User className="w-5 h-5 text-[#265073]" />
          </div>
        </div>
      </header>

      {/* Main Interview Area */}
      <div className="flex-1 flex flex-col items-center justify-center p-6 relative">
        {/* AI Interviewer Video */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="w-full max-w-4xl mb-6"
        >
          <div className="flex flex-col items-center mb-6">
            <motion.div
              animate={isSpeaking ? { scale: [1, 1.02, 1] } : {}}
              transition={{ repeat: isSpeaking ? Infinity : 0, duration: 1 }}
              className="w-80 h-60 bg-gradient-to-br from-[#2D9596] to-[#265073] rounded-2xl flex items-center justify-center mb-4 shadow-2xl border-4 border-white relative overflow-hidden"
            >
              <User className="w-24 h-24 text-white/80" />
              
              {isSpeaking && (
                <>
                  <motion.div
                    animate={{ scale: [1, 1.05, 1], opacity: [0.3, 0, 0.3] }}
                    transition={{ repeat: Infinity, duration: 1.5 }}
                    className="absolute inset-0 bg-[#2D9596] rounded-xl"
                  />
                  <div className="absolute top-4 left-4 bg-red-500 rounded-full px-3 py-1.5 flex items-center gap-2">
                    <Volume2 className="w-4 h-4 text-white animate-pulse" />
                    <span className="text-white text-xs">Đang hỏi...</span>
                  </div>
                </>
              )}
              
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent py-4 px-4">
                <p className="text-white text-lg">AI Interviewer</p>
                <p className="text-[#9AD0C2] text-sm">
                  {isSpeaking ? "Đang đọc câu hỏi..." : "Chờ bạn trả lời"}
                </p>
              </div>
            </motion.div>
          </div>

          {/* Question Card */}
          <motion.div
            key={currentQuestion.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white rounded-3xl shadow-2xl p-8 mb-6 border-4 border-[#2D9596] relative"
          >
            <div className="flex items-start gap-4 mb-4">
              <MessageSquare className="w-6 h-6 text-[#2D9596] flex-shrink-0" />
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                  <span className="text-xs bg-[#2D9596] text-white px-3 py-1 rounded-full">
                    Câu {currentQuestionIndex + 1}/{questions.length}
                  </span>
                  <span className="text-xs text-[#2D9596]">{currentQuestion.category}</span>
                </div>
                <p className="text-xl text-[#265073] leading-relaxed">{currentQuestion.text}</p>
              </div>
            </div>

            {/* Current transcript */}
            {isRecording && currentTranscript && (
              <div className="mt-4 p-4 bg-[#ECF4D6] rounded-xl border border-[#9AD0C2]">
                <p className="text-sm text-[#265073]/70 mb-1">Văn bản đang ghi:</p>
                <p className="text-sm text-[#265073]">{currentTranscript}</p>
              </div>
            )}

            {/* Recording timer */}
            {isRecording && (
              <motion.div
                initial={{ scale: 0 }}
                animate={{ scale: 1 }}
                className="absolute -top-4 right-8"
              >
                <div className="bg-red-500 text-white px-6 py-3 rounded-full shadow-lg flex items-center gap-3">
                  <Circle className="w-3 h-3 fill-white animate-pulse" />
                  <span className="text-lg tabular-nums">{formatTime(recordingTime)}</span>
                </div>
              </motion.div>
            )}
          </motion.div>
        </motion.div>

        {/* Candidate Video */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          className="absolute bottom-32 right-8 w-64 h-48 bg-gradient-to-br from-[#9AD0C2] to-[#2D9596] rounded-2xl shadow-2xl border-4 border-white overflow-hidden"
        >
          <div className="w-full h-full flex items-center justify-center relative">
            <User className="w-20 h-20 text-white/80" />
            
            {isRecording && (
              <>
                <motion.div
                  animate={{ scale: [1, 1.05, 1], opacity: [0.2, 0, 0.2] }}
                  transition={{ repeat: Infinity, duration: 1.5 }}
                  className="absolute inset-0 bg-red-500 rounded-xl"
                />
                <div className="absolute top-3 left-3 bg-red-500 rounded-full px-3 py-1.5 flex items-center gap-2">
                  <Circle className="w-3 h-3 fill-white animate-pulse" />
                  <span className="text-white text-xs">REC</span>
                </div>
              </>
            )}
            
            <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/70 to-transparent py-3 px-4">
              <p className="text-white">Bạn (Ứng viên)</p>
              {isRecording && (
                <p className="text-red-300 text-xs">Đang ghi âm...</p>
              )}
            </div>
          </div>
        </motion.div>

        {/* Control Bar */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="fixed bottom-8 left-1/2 transform -translate-x-1/2 bg-white/95 backdrop-blur-lg rounded-full shadow-2xl px-8 py-4 flex items-center gap-6 border-2 border-[#9AD0C2]"
        >
          {/* Record Button */}
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={isRecording ? stopRecording : startRecording}
            disabled={isSpeaking}
            className={`w-16 h-16 rounded-full flex items-center justify-center transition-all duration-300 shadow-lg ${
              isRecording
                ? "bg-red-500 hover:bg-red-600"
                : isSpeaking
                ? "bg-gray-300 cursor-not-allowed"
                : "bg-[#265073] hover:bg-[#2D9596]"
            }`}
          >
            {isRecording ? (
              <MicOff className="w-7 h-7 text-white" />
            ) : (
              <Mic className="w-7 h-7 text-white" />
            )}
          </motion.button>

          {/* Next Button */}
          {!isRecording && answers.length > currentQuestionIndex && (
            <motion.button
              initial={{ scale: 0 }}
              animate={{ scale: 1 }}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={nextQuestion}
              className="w-14 h-14 bg-[#2D9596] hover:bg-[#265073] rounded-full flex items-center justify-center transition-all duration-300"
              title="Câu tiếp theo"
            >
              <ChevronRight className="w-6 h-6 text-white" />
            </motion.button>
          )}

          {/* Repeat Question */}
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={repeatQuestion}
            disabled={isRecording || isSpeaking}
            className="w-14 h-14 bg-[#265073] hover:bg-[#2D9596] rounded-full flex items-center justify-center transition-all duration-300 disabled:bg-gray-300 disabled:cursor-not-allowed"
            title="Hỏi lại"
          >
            <RotateCcw className="w-6 h-6 text-white" />
          </motion.button>

          {/* View Transcript */}
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => setShowTranscript(!showTranscript)}
            className="w-14 h-14 bg-[#265073] hover:bg-[#2D9596] rounded-full flex items-center justify-center transition-all duration-300"
            title="Xem câu hỏi"
          >
            <FileText className="w-6 h-6 text-white" />
          </motion.button>

          {/* Exit */}
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={exitInterview}
            className="w-14 h-14 bg-red-500 hover:bg-red-600 rounded-full flex items-center justify-center transition-all duration-300"
            title="Thoát"
          >
            <LogOut className="w-6 h-6 text-white" />
          </motion.button>
        </motion.div>

        {/* Transcript Modal */}
        <AnimatePresence>
          {showTranscript && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-6"
              onClick={() => setShowTranscript(false)}
            >
              <motion.div
                initial={{ scale: 0.9, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.9, opacity: 0 }}
                onClick={(e) => e.stopPropagation()}
                className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-auto p-6"
              >
                <h3 className="text-2xl text-[#265073] mb-4">Danh sách câu hỏi</h3>
                <div className="space-y-3">
                  {questions.map((q, index) => (
                    <div
                      key={q.id}
                      className={`p-4 rounded-xl border-2 ${
                        index === currentQuestionIndex
                          ? "bg-[#2D9596] border-[#2D9596] text-white"
                          : index < currentQuestionIndex
                          ? "bg-[#ECF4D6] border-[#9AD0C2] text-[#265073]"
                          : "bg-gray-50 border-gray-200 text-gray-400"
                      }`}
                    >
                      <div className="flex items-start gap-3">
                        <span className="flex-shrink-0 w-6 h-6 rounded-full bg-white/20 flex items-center justify-center text-sm">
                          {index + 1}
                        </span>
                        <p className="text-sm">{q.text}</p>
                      </div>
                    </div>
                  ))}
                </div>
                <button
                  onClick={() => setShowTranscript(false)}
                  className="w-full mt-6 py-3 bg-[#265073] text-white rounded-xl hover:bg-[#2D9596] transition-all duration-300"
                >
                  Đóng
                </button>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Permission Modal */}
        <AnimatePresence>
          {showPermissionModal && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-6"
            >
              <motion.div
                initial={{ scale: 0.9, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.9, opacity: 0 }}
                className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-8"
              >
                <div className="text-center">
                  <div className="w-20 h-20 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <MicOff className="w-10 h-10 text-red-500" />
                  </div>
                  <h3 className="text-2xl text-[#265073] mb-3">Cần quyền truy cập Microphone</h3>
                  <p className="text-[#2D9596] mb-6 leading-relaxed">
                    Để sử dụng tính năng phỏng vấn bằng giọng nói, bạn cần cấp quyền truy cập microphone.
                  </p>

                  <div className="flex gap-3">
                    <button
                      onClick={() => setShowPermissionModal(false)}
                      className="flex-1 py-3 bg-gray-200 text-[#265073] rounded-xl hover:bg-gray-300 transition-all duration-300"
                    >
                      Đóng
                    </button>
                    <button
                      onClick={() => {
                        setShowPermissionModal(false);
                        window.location.reload();
                      }}
                      className="flex-1 py-3 bg-[#2D9596] text-white rounded-xl hover:bg-[#265073] transition-all duration-300"
                    >
                      Tải lại trang
                    </button>
                  </div>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
