import { Interview } from '../../pages/EmployerInterviews';

export const mockInterviews: Interview[] = [
  {
    id: 'int1',
    candidateId: 'cand1',
    candidateName: 'Nguyễn Minh Tuấn',
    candidateAvatar: 'https://i.pravatar.cc/150?img=12',
    candidateEmail: 'minhtuan.dev@gmail.com',
    jobTitle: 'Senior Full Stack Developer',
    jobId: 'job1',
    matchScore: 94,
    date: '2025-11-25',
    time: '14:00',
    duration: 60,
    type: 'online',
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    interviewer: 'Trần Văn A',
    interviewerRole: 'Technical Lead',
    candidateNotes: 'Vui lòng chuẩn bị trước về kinh nghiệm microservices và cloud architecture.',
    internalNotes: 'Ứng viên có kinh nghiệm tốt, cần đánh giá sâu về leadership skills.',
    status: 'confirmed',
  },
  {
    id: 'int2',
    candidateId: 'cand2',
    candidateName: 'Trần Thu Hương',
    candidateAvatar: 'https://i.pravatar.cc/150?img=5',
    candidateEmail: 'thuhuong.fe@gmail.com',
    jobTitle: 'Frontend Developer (React)',
    jobId: 'job2',
    matchScore: 88,
    date: '2025-11-28',
    time: '14:00',
    duration: 45,
    type: 'online',
    meetingLink: 'https://meet.google.com/xyz-abcd-efg',
    interviewer: 'Nguyễn Thị B',
    interviewerRole: 'HR Manager',
    candidateNotes: 'Phỏng vấn kỹ thuật và cultural fit. Vui lòng chuẩn bị portfolio.',
    internalNotes: 'Portfolio rất đẹp, UI/UX sense tốt.',
    status: 'confirmed',
  },
  {
    id: 'int3',
    candidateId: 'cand3',
    candidateName: 'Lê Hoàng Nam',
    candidateAvatar: 'https://i.pravatar.cc/150?img=33',
    candidateEmail: 'hoangnam.devops@gmail.com',
    jobTitle: 'DevOps Engineer',
    jobId: 'job3',
    matchScore: 91,
    date: '2025-11-26',
    time: '10:00',
    duration: 60,
    type: 'online',
    meetingLink: 'https://zoom.us/j/123456789',
    interviewer: 'Phạm Văn C',
    interviewerRole: 'DevOps Lead',
    candidateNotes: 'Phỏng vấn kỹ thuật về K8s, Docker, CI/CD.',
    internalNotes: 'Kinh nghiệm tốt với K8s và CI/CD.',
    status: 'sent',
  },
  {
    id: 'int4',
    candidateId: 'cand4',
    candidateName: 'Phạm Thị Lan',
    candidateAvatar: 'https://i.pravatar.cc/150?img=9',
    candidateEmail: 'thilan.designer@gmail.com',
    jobTitle: 'UI/UX Designer',
    jobId: 'job4',
    matchScore: 85,
    date: '2025-11-27',
    time: '15:30',
    duration: 45,
    type: 'onsite',
    location: 'Văn phòng công ty - Tầng 12, Tòa nhà ABC, Quận 1, TP.HCM',
    interviewer: 'Lê Thị D',
    interviewerRole: 'Design Lead',
    candidateNotes: 'Phỏng vấn onsite. Vui lòng mang theo portfolio và thiết bị làm việc.',
    internalNotes: 'Cần đánh giá design thinking và collaboration skills.',
    status: 'pending',
  },
  {
    id: 'int5',
    candidateId: 'cand5',
    candidateName: 'Vũ Đức Anh',
    candidateAvatar: 'https://i.pravatar.cc/150?img=14',
    candidateEmail: 'ducanh.backend@gmail.com',
    jobTitle: 'Backend Developer (Node.js)',
    jobId: 'job5',
    matchScore: 79,
    date: '2025-11-29',
    time: '09:00',
    duration: 60,
    type: 'online',
    meetingLink: 'https://meet.google.com/def-ghij-klm',
    interviewer: 'Hoàng Văn E',
    interviewerRole: 'Backend Lead',
    candidateNotes: 'Phỏng vấn kỹ thuật về Node.js, databases, API design.',
    internalNotes: 'Có kinh nghiệm tốt nhưng cần kiểm tra system design.',
    status: 'sent',
  },
  {
    id: 'int6',
    candidateId: 'cand6',
    candidateName: 'Hoàng Minh Châu',
    candidateAvatar: 'https://i.pravatar.cc/150?img=20',
    candidateEmail: 'minhchau.qa@gmail.com',
    jobTitle: 'QA Engineer',
    jobId: 'job6',
    matchScore: 82,
    date: '2025-11-24',
    time: '16:00',
    duration: 45,
    type: 'online',
    meetingLink: 'https://meet.google.com/nop-qrst-uvw',
    interviewer: 'Đặng Văn F',
    interviewerRole: 'QA Lead',
    candidateNotes: 'Phỏng vấn về automation testing và test strategy.',
    internalNotes: 'Có kinh nghiệm automation với Selenium.',
    status: 'completed',
  },
  {
    id: 'int7',
    candidateId: 'cand7',
    candidateName: 'Đỗ Quang Huy',
    candidateAvatar: 'https://i.pravatar.cc/150?img=15',
    candidateEmail: 'quanghuy.mobile@gmail.com',
    jobTitle: 'Mobile Developer (React Native)',
    jobId: 'job7',
    matchScore: 87,
    date: '2025-11-30',
    time: '11:00',
    duration: 60,
    type: 'online',
    meetingLink: 'https://zoom.us/j/987654321',
    interviewer: 'Vũ Thị G',
    interviewerRole: 'Mobile Lead',
    candidateNotes: 'Phỏng vấn về React Native, mobile architecture.',
    internalNotes: 'Kinh nghiệm tốt với React Native và native modules.',
    status: 'sent',
  },
  {
    id: 'int8',
    candidateId: 'cand8',
    candidateName: 'Ngô Thị Mai',
    candidateAvatar: 'https://i.pravatar.cc/150?img=25',
    candidateEmail: 'thimai.pm@gmail.com',
    jobTitle: 'Product Manager',
    jobId: 'job8',
    matchScore: 90,
    date: '2025-11-23',
    time: '13:30',
    duration: 45,
    type: 'online',
    meetingLink: 'https://meet.google.com/xyz-mnop-qrs',
    interviewer: 'Trịnh Văn H',
    interviewerRole: 'CEO',
    candidateNotes: 'Phỏng vấn về product thinking và roadmap planning.',
    internalNotes: 'Có kinh nghiệm tốt với B2B products.',
    status: 'cancelled',
  },
];

export const jobOptions = [
  { id: 'job1', title: 'Senior Full Stack Developer' },
  { id: 'job2', title: 'Frontend Developer (React)' },
  { id: 'job3', title: 'DevOps Engineer' },
  { id: 'job4', title: 'UI/UX Designer' },
  { id: 'job5', title: 'Backend Developer (Node.js)' },
  { id: 'job6', title: 'QA Engineer' },
  { id: 'job7', title: 'Mobile Developer (React Native)' },
  { id: 'job8', title: 'Product Manager' },
];

export const candidateOptions = [
  { id: 'cand1', name: 'Nguyễn Minh Tuấn', avatar: 'https://i.pravatar.cc/150?img=12', matchScore: 94, jobTitle: 'Senior Full Stack Developer' },
  { id: 'cand2', name: 'Trần Thu Hương', avatar: 'https://i.pravatar.cc/150?img=5', matchScore: 88, jobTitle: 'Frontend Developer (React)' },
  { id: 'cand3', name: 'Lê Hoàng Nam', avatar: 'https://i.pravatar.cc/150?img=33', matchScore: 91, jobTitle: 'DevOps Engineer' },
  { id: 'cand4', name: 'Phạm Thị Lan', avatar: 'https://i.pravatar.cc/150?img=9', matchScore: 85, jobTitle: 'UI/UX Designer' },
  { id: 'cand5', name: 'Vũ Đức Anh', avatar: 'https://i.pravatar.cc/150?img=14', matchScore: 79, jobTitle: 'Backend Developer (Node.js)' },
];

export const interviewerOptions = [
  { id: 'emp1', name: 'Trần Văn A', role: 'Technical Lead' },
  { id: 'emp2', name: 'Nguyễn Thị B', role: 'HR Manager' },
  { id: 'emp3', name: 'Phạm Văn C', role: 'DevOps Lead' },
  { id: 'emp4', name: 'Lê Thị D', role: 'Design Lead' },
  { id: 'emp5', name: 'Hoàng Văn E', role: 'Backend Lead' },
  { id: 'emp6', name: 'Đặng Văn F', role: 'QA Lead' },
  { id: 'emp7', name: 'Vũ Thị G', role: 'Mobile Lead' },
  { id: 'emp8', name: 'Trịnh Văn H', role: 'CEO' },
];
